#!/usr/bin/env bash
# with this script we can copy file from local host to server
# in secure way by using "scp"

arg_number=$#

if [ $arg_number -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit
fi

scp -i $4 $1 $3@$2:~/
