#!/usr/bin/env bash
# with this script we change the content of nginx main web page
# to hello world!

sudo apt update

sudo apt-get -y install nginx

echo "Hello World!" > /var/www/html/index.nginx-debian.html

sudo nginx -s reload

exit
