#!/usr/bin/env bash
# with this script we change the content of nginx main web page
# to hello world!

sudo apt update

sudo apt-get -y install nginx

echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

sudo nginx -s reload

sudo service nginx restart
