#!/usr/bin/env bash
# redirect from redirect_me to URL=youtube permanently

redirect="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"


sudo apt-get update

sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null

sudo sed -i "29i $redirect" /etc/nginx/sites-available/default

sudo nginx -s reload
