#!/usr/bin/env bash
# add custome error page

redirect="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"

sudo apt-get update

sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null

sudo sed -i "29i $redirect" /etc/nginx/sites-available/default


echo "Ceci n'est pas une page\n" | sudo tee /var/www/html/404.html > /dev/null

sudo sed -i '31i\ \ \ error_page 404 /404.html;\n\ \ \ location = /404.html {\n\ \ \ \ \ internal;\n\ \ \ }' /etc/nginx/sites-available/default
sudo nginx -s reload
