#!/usr/bin/env bash

sudo apt-get update

sudo apt-get install -y nginx

header="\\\tadd_header X-Served-By {$hostname};"

sudo sed -i "36i /server {/a \\\t \t$header" /etc/nginx/sites-available/default

sudo nginx -s reload

sudo service nginx restart

