#!/usr/bin/env bash
# this script for installing nginx on serever and adding a new header
# to the srever
sudo apt-get update

sudo apt-get install -y nginx

HOSTNAME=$(hostname)
FONFIG_FILE="/etc/nginx/sites-available/default"

header="add_header X-Served-By $HOSTNAME;"

if ! grep -q "add_header X-Served-By" $FONFIG_FILE; then
    sudo sed -i "/server {/a \\\t$header" $FONFIG_FILE
fi

sudo nginx -s reload

sudo service nginx restart
