#!/usr/bin/env bash
# install HAProxy and Configure HAproxy so that it send traffic to web-01 and web-02
# using load balance round robing algorithm

sudo apt-get update
sudo apt-get install -y haproxy

STUDENT_ID="269106"
WEB_01="${STUDENT_ID}-web-01"
WEB_02="${STUDENT_ID}-web-02"


sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF

frontend http_front
    bind *:80
    mode http
    default_backend webservers

backend webservers
    balance roundrobin
    mode http
    server ${WEB_01} 35.175.64.12:80 check
    server ${WEB_02} 18.234.192.156:80 check
EOF
# this another way or spining a haproxy file
# sudo haproxy -f haproxy.cfg
sudo service haproxy restart
