#!/usr/bin/env bash
# ping an address IP 5 times, and if argument if empty print erro msg

ip_adress=$1

if [ -z "$ip_adress" ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"

else
    ping -c 5 "$ip_adress"
fi
