#!/usr/bin/env bash
# to fix the problem with need to make sure the container port is mapped to host port
# chnage the port to 80
sudo apt update
sudo apt -y install docker
sudo docker
sudo docker run -d --name testnginx -p 80:80 nginx

