#!/usr/bin/env bash
# to fix the problem with need to make sure the container port is mapped to host port
# chnage the port to 80
# sudo apt update
# sudo apt -y install docker
running=$(sudo docker ps -q)
if [ -n "$running" ]; then
    sudo docker stop "$running" > /dev/null
    sudo docker rm "$running" > /dev/null
fi
sudo docker run -d --name myInginx -p 80:80 nginx
