#!/usr/bin/env bash
#create file /var/run/myscript.pid

file=/var/run/myscript.pid
touch /var/run/myscript.pid
pid=$(pgrep -f /var/run/myscript.pid)
echo "$pid" >> $file

function hate()
{
    echo "I hate the kill command"
}

function love()
{
    echo "Y U no love me?!"
}

function delete()
{
    rm /var/run/myscript.pid
    exit 1
}

while true
do
    echo "To infinity and beyond"
    
    trap hate SIGTERM
    trap love SIGINT
    trap delete SIGQUIT
    trap delete SIGTERM
done
