#!/usr/bin/env bash
# this script for listenning to linux singls like SIGTERM
# and then print I am invincible!!! when single receivd

function handl_signl()
{
    echo "I am invincible!!!"
}

function handl_p_signl()
{
    echo "killed"
    exit 0
}

while true
do
    echo "To infinity and beyond"
    sleep 2
    trap handl_signl SIGTERM
    trap handl_p_signl SIGUSR1
done
