#!/usr/bin/env bash
# in this script we read from file named password and parse it's data
# by using cut command to cut from each line what we want.

file="/etc/passwd"

while IFS= read -r line
do
    echo "$line" | cut -d ":" -f 1,3,6 
done < "$file"
