#!/usr/bin/env bash
# Iterate using a while loop to print best Scholl
# except when count is 4 we print bad luck and when count=8 good look

count=1

while [ $count -le 10 ]
do
    if [ $count -eq 4 ]; then
        echo "bad luck"
    elif [ $count -eq 8 ]; then
        echo "good luck"
    else
        echo "$str"
    fi
    
    ((count++))
done
