#!/usr/bin/env bash
# Iterate using a while loop to print numbers from 0 to 60
# minute and from 0 to 12 hours

count=0
hour=1

while true
do
    if [ $count -eq 0 ]; then
        echo "Hour: 0"
    elif [ $count -eq 60 ]; then
        echo "Hour: $hour"
        ((hour++))
        count=0
    else
        echo "$count"
    fi
    ((count++))
done
