#!/usr/bin/env bash
# Iterate using a while loop to print numbers from 0 to 60
# minute and from 0 to 12 hours

count=0
count2=1

while [ $count -le 60 ]
do
    if [ $count -eq 0 ]; then
        echo "Hour: 0"
    elif [ $count -eq 60 ]; then
        echo "Hour: 1"
        while [ $count2 -le 12 ]
        do 
            echo "$count2"
            ((count2++))
        done
    else
        echo "$count"
    fi
    ((count++))
done
