#!/usr/bin/env bash
# this script for checking existsance of a file and if it's empty
# and if he's a regular file 

file="school"

if test -f "$file" || test -d $file
then
    echo "school file exists"
    if [ -s "$file" ]; then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi
    if [ -f "$file" ]; then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
