#!/usr/bin/env bash
# with this script we can setup firewall on out server .
# by dening all incomig traffic except on port 22/80/443
# and allowing outgoing traffic
sudo apt update

sudo apt install -y ufw

sudo ufw enable

sudo ufw allow 22/tcp

sudo ufw allow 80/tcp

sudo ufw allow 443/tcp

sudo ufw default deny incoming

sudo ufw default allow outgoing

sudo ufw reload
