#!/usr/bin/env bash
# change ip adress of localhost and facebook on the host.
cp /etc/hosts ~/hosts.new
sudo sed -i 's/127\.0\.0\.1/127\.0\.0\.2/g' ~/hosts.new
#echo "8.8.8.8       157.240.11.35" >> ~/hosts.new
sudo sh -c 'echo "8.8.8.8 facebook.com" >> ~/hosts.new'
cp -f ~/hosts.new /etc/hosts
