#!/usr/bin/env bash
# change ip adress of localhost and facebook on the host.
cp /etc/hosts ~/hosts.new
sudo sed -i 's/127\.0\.0\.1/127\.0\.0\.2/g' ~/hosts.new
echo "8.8.8.8       www.facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
