#!/usr/bin/env bash
# in this script we create apache container with name holbertonschool and host port 8080
# so we can acces to this container on local host
# we execute bash command on the container
# navigate to htdocs were the main page it stored
# use echo to change the content of the page to Hello Holberton
# exit from the continer

sudo docker run --name holbertonschool -d -p 8080:80 httpd

# sudo docker exec -it holbertonschool bash
# 
# echo "Hello Holberton" | sudo tee /usr/local/apache2/htdocs/index.html > /dev/null

sudo docker exec holbertonschool bash -c 'echo "Hello Holberton" > /usr/local/apache2/htdocs/index.html'
